baseURL = "https://jonyig.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Jonny"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.1.X"

[menu]
  [[menu.main]]
    identifier = "文章盒"
    # you can add extra information before the name (HTML format is allowed), such as icons
    pre = ""
    name = "文章盒"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "文章盒"
    weight = 1
  [[menu.main]]
    identifier = "標籤盒"
    pre = ""
    name = "標籤盒"
    url = "/tags/"
    title = "標籤盒"
    weight = 2
  [[menu.main]]
    identifier = "分類盒"
    pre = ""
    name = "分類盒"
    url = "/categories/"
    title = "分類盒"
    weight = 3

